name: GitHub-Profile-Summary-Cards

on:
  schedule: # 1日1回更新
    - cron: "0 0 * * *"
  workflow_dispatch: # 手動実行も可

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate profile summary cards
        uses: vn7n24fzkq/github-profile-summary-cards@v0.5.0
        with:
          username: shogo-tsunoda
          theme: gruvbox
          auth: ${{ secrets.PERSONAL_TOKEN }}

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add profile-summary-card-output
          git commit -m "chore: update profile summary cards" || echo "no changes"
          git push
